# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
       # with:
        #   registry: us-central1-maven.pkg.dev
        #   username: oauth2accesstoken
        #   password: ${{ steps.auth.outputs.access_token }}        

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Login to Artifact Registry
        run: |
            gcloud config set account github-action@da-poc-2022.iam.gserviceaccount.com
              
            gcloud auth activate-service-account github-action@da-poc-2022.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS
 
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Publish JAR
        run: mvn --batch-mode release:prepare release:perform -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
